<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HttpMultipartParser" Version="8.4.0" />
    <PackageReference Include="JWT" Version="10.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DependencyInjection\DependencyInjection.csproj" />
    <ProjectReference Include="..\KJson\KJson.csproj" />
    <ProjectReference Include="..\KLogger\KLogger.csproj" />
  </ItemGroup>

</Project>
